### PR TITLE
Vagrant devstack wiki page gives a 404. This fixes the link.

### PR DESCRIPTION
**Pull request by natea**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @natea! I've created [OSPR-3142](https://openedx.atlassian.net/browse/OSPR-3142) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@natea Thank you for your contribution.

**Comment by natabene** [comment]
@nedbat Can you give this a quick look?

**Comment by openedx-webhooks** [comment]
@natea 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/389&entry.1484655318=https://github.com/natea&entry.752974735=2019-02-26+23:56&entry.1917517419=2019-02-27+19:10&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
