### PR TITLE
add config for sharing src folder in sync containers

### PR DESCRIPTION
**Pull request by danialmalik**
## Background:
I use docker-sync on my Macbook to have things a little bit faster but the problem is that there is no `src` folder shared in case of synced containers.

This PR adds `src` directory in the synced containers for sharing files with the host system.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @danialmalik! I've created [OSPR-4605](https://openedx.atlassian.net/browse/OSPR-4605) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@danialmalik Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by danialmalik** [comment]
@natabene it's ready now. I've resolved the conflicts

**Comment by natabene** [comment]
@danialmalik Thanks for letting me know. @jmbowman @kdmccormick Could either of you review this when you have a chance?

**Review by jinder1s — APPROVED** [review]
Hi,
the contents of this PR look good to go. Though question, have you considered using devstack with nfs on mac? Internally, docker-sync hasn't worked for us and nfs approach seems more promising(look up nfs in devstack readme for details)

**Comment by jinder1s** [comment]
Also, let me know if you need to make any changes, otherwise I will merge this PR soon.

**Comment by danialmalik** [comment]
@jinder1s thanks for reviewing the PR. 
I've just added the sync volume to forum, registrar and grade book service. It's ready from my side now.

**Comment by danialmalik** [comment]
And I didn't try the nfs method, I just gave sync a shot and it made things a little bit better (still no match for Linux though). I'll try nfs too. Maybe that will make things even faster.
thanks

**Comment by openedx-webhooks** [comment]
@danialmalik 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/541&entry.1484655318=https://github.com/danialmalik&entry.752974735=2020-05-29+06:13&entry.1917517419=2020-06-23+16:31&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
