### PR TITLE
build: add edx-community-bot workflow

### PR DESCRIPTION
**Pull request by sarina**
@stvstnfrd 

@edx/open-release-maintainers FYI - you'll need to pull this patch onto any Lilac branches you have to get the community bot to run right

I've completed each of the following or determined they are not applicable:

- [x] Made a plan to communicate any major developer interface changes (or N/A)

### CODE REVIEW

**Comment by sarina** [comment]
@edx/open-release-maintainers : should I ignore these failing tests?

**Comment by arbrandes** [comment]
ACK, @sarina, thanks!

Oh, and regarding failing tests: good question.  I haven't kept up with devstack CI, so not sure.  How are the tests doing in master?

**Comment by cmltaWt0** [comment]
Thanks, @sarina !

> should I ignore these failing tests?

Let us some time to figure it out.
Checking it in this sample [PR](https://github.com/edx/devstack/pull/812)

**Comment by cmltaWt0** [comment]
Sample PR's [Checks](https://github.com/edx/devstack/pull/812) also fails. So looks like this PR can be merged and CI fails can be ignored since the changes doesn't have anything to do with fails.

@arbrandes what do you think?

**Comment by arbrandes** [comment]
@cmltaWt0, works for me!

**Pull request merged**
