### PR TITLE
fix: Moving learning app to release section.

### PR DESCRIPTION
**Pull request by ztraboo**
Separated this out from #880 

Made `frontend-app-learning` as a default repo to install on devstack.

@cmltaWt0

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ztraboo! I've created [OSPR-6381](https://openedx.atlassian.net/browse/OSPR-6381) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by kdmccormick** [comment]
Thanks @ztraboo ! Once the CLA is sorted I'll be happy to take a look.

**Comment by natabene** [comment]
@ztraboo Thanks for opening this PR. I will post an update here once your CLA has been processed.

**Comment by natabene** [comment]
@ztraboo Thanks for getting a new CLA signed, you are all set now. The check should clear with the next commit.

**Comment by kdmccormick** [comment]
@ztraboo could you rebase? Pushing a new commit should get both of those failing checks to run again.

**Comment by ztraboo** [comment]
@natabene Thanks for letting me know about the CLA signed processes. It looks like the `openedx/cla` check passed.

@kdmccormick 

> @ztraboo could you rebase? Pushing a new commit should get both of those failing checks to run again.

Sorry for the delay. I just rebased my branch onto `open-release/maple.master`.

**Comment by ztraboo** [comment]
@kdmccormick 
Looks like an issue with the `CLI test / run_ci` with the following. Any idea how to fix this?
> Error creating machine: Error in driver during machine creation: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

**Review by kdmccormick — APPROVED** [review]
@ztraboo Honestly, no idea what that error is. It's definitely not connected to your change, though.

**Comment by kdmccormick** [comment]
Looks like the check has been failing on `open-release/maple.master` for a while. I'm going to merge this PR in spite of it.

**Comment by openedx-webhooks** [comment]
@ztraboo 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/devstack&entry.867055334=https://github.com/openedx/devstack/pull/881&entry.1484655318=https://github.com/ztraboo&entry.752974735=2022-01-12+16:29&entry.1917517419=2022-02-02+18:43&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
