### PR TITLE
Replaced rsync with unison

### PR DESCRIPTION
**Pull request by clintonb**
This will allow for two-way syncing, allowing us to run commands that create files (e.g. migrations) inside the containers.

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/docker-devstack-working-group please review

**Comment by clintonb** [comment]
...and try it out!

**Comment by gsong** [comment]
@clintonb Will this require installation of Unison on the host machine? I imagine yes?

**Comment by robrap** [comment]
@gsong I think the installation of docker-sync forced you to install unison even when we were only using rsync.  Did you not have that experience?
UPDATE: When I first installed, I got:
```
Shall we continue - DID you read it? (y/N) y
       error  Could not find unison binary in path. Please install it, e.g. using "brew install unison"
```

**Comment by clintonb** [comment]
@robrap is correct.

However, I really don't like the startup penalty with unison. It takes a noticeable amount of time (over 1 minute) to sync all the data *before* the containers even start.

**Comment by clintonb** [comment]
This is no longer necessary given that Docker Sync has a new strategy: https://github.com/EugenMayer/docker-sync/wiki/Testin-the-new-Native-OSX-strategy

**Pull request closed without merging**
