### PR TITLE
[WIP] Adding a volume in which to clone the theming repos

### PR DESCRIPTION
**Pull request by felipemontoya**
## Description

This PR adds a volume where comprehensive theme repositories are supposed to be cloned.

Then it would be quite easy to update `devstack.py` to include some configurations like:
```
DEFAULT_SITE_THEME = "my_theme_name"
ENABLE_COMPREHENSIVE_THEMING = True
COMPREHENSIVE_THEME_DIRS = [
    "/edx/app/openedx-themes/my_theme_repo",
] 
```
And that would be all what is needed to start developing a comprehensive theme, outside of the main `edx-platform` repo.

## Motivation

I tried to find a good location for this, and the only reference I found to themes was the `Makefile.edx.dev.clone_whitelabel` target. That however relies on the developer having access to a private repo.

This PR wants to spark the discussion about some best practices around how developers in the community are supposed to work with this docker based devstack.

## Reviewers

- [ ] I have no idea who would be a good fit to review this.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @felipemontoya! I've created [OSPR-2305](https://openedx.atlassian.net/browse/OSPR-2305) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/devstack/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@edx/platform-team Can you help move this forward?

**Comment by doctoryes** [comment]
@felipemontoya I added the Makefile.edx file and the accompanying docker-compose-themes.yml in order to enable edx.org-based testing of "whitelabel" themed sites within Docker devstack. You're correct that it's currently hard-coded to assume one has access to a private edx.org repository.

A good approach to making this solution more general might be to implement a check in the Makefile that checks for the existence of a `docker-compose-themes.yml` (or `docker-compose-theme-vols.yml` or `docker-compose-openedx-themes.yml` or the like) and layer it onto the docker-compose command in the `dev.up` target only if the file exists. Then Open edX installs could optionally create this file and place the volumes/paths they use within it.

The volume addition shouldn't go into the `docker-compose-host.yml` file, as that file should only contain known volume paths to public repos. And it's trivial to layer on more docker-compose YML files onto a docker-compose command.

**Comment by macdiesel** [comment]
To echo Doctoryes' statement, I think the correct approach here would be to do the docker compose layering with the makefile. I would approve a PR that took this approach. I am going to close this PR.

**Comment by openedx-webhooks** [comment]
@felipemontoya Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/282&entry.1484655318=https://github.com/felipemontoya&entry.752974735=2018-03-15+22:22&entry.1917517419=2018-03-26+18:51&entry.2133058324=No) so we can improve your experience in the future.

**Comment by felipemontoya** [comment]
Sorry, I didn't address @doctoryes comments in time, but I am ok with the layered approach. I'll take a few days off because of easter, but will take a look once I'm back next week

**Pull request closed without merging**
