### PR TITLE
Improve: fix typo in makefile

### PR DESCRIPTION
**Pull request by asamolion**
Small typo fix in Makefile.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @asamolion! I've created [OSPR-2704](https://openedx.atlassian.net/browse/OSPR-2704) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@asamolion This is great, thank you for your contribution. As a first step, please sign and send the contributor agreement.

**Comment by asamolion** [comment]
@natabene I've signed and sent the agreement to legal@edx.org. Please confirm and verify.

Regards.

**Comment by natabene** [comment]
@asamolion Thank you for sending the signed agreement. Please give our legal team a day or two to process it. I will let you know once it is done.

**Comment by asamolion** [comment]
@natabene Any updates on this?

**Comment by natabene** [comment]
@asamolion Let me check again with the team, and I will post an update asap.

**Comment by natabene** [comment]
@macdiesel Can you give this a look when you have a chance?

**Comment by openedx-webhooks** [comment]
@asamolion 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/344&entry.1484655318=https://github.com/asamolion&entry.752974735=2018-10-17+01:53&entry.1917517419=2018-10-29+20:22&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
