### PR TITLE
[BD-14] Add elasticsearch as a Studio dependency

### PR DESCRIPTION
**Pull request by kdmccormick**
It is need by the newly-improved Studio API: `/api/libraries/v2/`

See https://github.com/edx/edx-platform/pull/24530

@mavidser

### CODE REVIEW

**Review by mavidser — APPROVED** [review]
Thanks @kdmccormick, this looks good :+1:.

**Comment by kdmccormick** [comment]
Great! I'll let this sit until `ENABLED_LIBRARY_INDEX` is turned on for devstack.

**Comment by stvstnfrd** [comment]
@kdmccormick BTW: I make this same change (along with LMS, and albeit to elasticsearch7), here: https://github.com/edx/devstack/pull/623

**Comment by kdmccormick** [comment]
Closing for now due to BD-14 pause.

**Pull request closed without merging**
