### PR TITLE
Revert "feat: adding metrics collections to more targets (#758)"

### PR DESCRIPTION
**Pull request by jdmulloy**
This reverts commit d1edbe7573aa56d39408ae2d41c46f25b5893443.

Something about this commit broke "make dev.provision"

I got the following with this commit and reverting this commit fixed it.

```
 Provisioning lms...
+ ./provision-lms.sh
++ apps=(lms studio)
++ ./load-db.sh edxapp
Loading the edxapp database...
Error: No such container: make[2]: Entering directory '/home/jdmulloy/git/edx-devstack/devstack'
2ef7bfa2ae68239ef7ca6ecf595a62df076774187671e21c741d3719c189cb18
make[2]: Leaving directory '/home/jdmulloy/git/edx-devstack/devstack'
make[1]: *** [Makefile:242: impl-dev.provision] Error 1
make[1]: Leaving directory '/home/jdmulloy/git/edx-devstack/devstack'
(venv_devstack) (⎈ tools-edx-eks:celery-monitoring) ➜ ~/git/edx-devstack/devstack git:(master) ✗ $
```

----

I've completed each of the following, or confirmed they do not apply to this PR:

- [ ] Tested on both Mac and Linux (if changed Makefile or shell scripts)
    - Already tested on: *[my OS here]*
    - Testing instructions: *[commands and expected behavior]*
- [ ] Made a plan to communicate any major developer interface changes

### CODE REVIEW

**Comment by timmc-edx** [comment]
So `make dev.provision` succeeds for you on the commit immediately proceeding that one?

**Comment by jdmulloy** [comment]
@timmc-edx It works for me on this branch. It seems to specifically fail when run under the python wrapper script.

**Comment by timmc-edx** [comment]
I think I found it. `load-db.sh` calls `make -s` but leaves off the `--no-print-directory` that becomes important once there's another level of make recursion. We use recursive calls in other places, but never hit this until now. I'll see if making this change fixes things.

**Comment by timmc-edx** [comment]
PR is up here: https://github.com/edx/devstack/pull/766

But... the next question is why CI didn't catch this.

**Comment by timmc-edx** [comment]
@jdmulloy Give it another try on latest master -- should be fixed now!

**Comment by jdmulloy** [comment]
@timmc-edx works on current master. Thanks. Closing.

**Pull request closed without merging**
