### PR TITLE
Using cached volume configuration to improve performance

### PR DESCRIPTION
**Pull request by clintonb**
See https://docs.docker.com/docker-for-mac/osxfs-caching/ for details.

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/docker-devstack-working-group please review

**Comment by clintonb** [comment]
It seems the Docker version on Travis does not support the `cached` configuration, and is not dumb/smart enough to ignore it.

**Comment by gsong** [comment]
@clintonb Do we still need docker-sync if we're using `cached`?

**Comment by clintonb** [comment]
@gsong Maybe not. A very quick manual test provided performance that is on par with Docker Sync.  I'll run some [loadtests](https://github.com/edx/edx-load-tests/tree/master/loadtests/devstack) when I have time.

**Comment by clintonb** [comment]
Load test results updated at https://openedx.atlassian.net/wiki/display/OpenDev/Load+Tests.

Performance is about on par with Docker Sync.

**Comment by gsong** [comment]
@clintonb Sweet!

**Comment by robrap** [comment]
@clintonb FYI: I will try to test debugging in PyCharm soon with:
1. Vagrant devstack,
2. This change with docker-sync, and 
3. This change without docker-sync.
I'll let you know what I find.

**Comment by clintonb** [comment]
This change eliminates the need for Docker Sync. I haven't used Docker Sync in a few weeks. I'll share more later today.

**Comment by robrap** [comment]
@clintonb Right.  I was just recommending another possible performance test to ensure that this really does eliminate the need for docker-sync, since I was running into performance problems around this earlier.

**Pull request merged**
