### PR TITLE
ci: test merge

### PR DESCRIPTION
**Pull request by cmltaWt0**
----

I've completed each of the following or determined they are not applicable:

- [ ] Made a plan to communicate any major developer interface changes (or N/A)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @cmltaWt0! I've created [OSPR-6404](https://openedx.atlassian.net/browse/OSPR-6404) to keep track of it in JIRA.

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Comment by nedbat** [comment]
Testing the automerge workflow...

**Comment by openedx-webhooks** [comment]
@jmbowman: thought you might like to know that cmltaWt0 merged this pull request.

**Comment by openedx-webhooks** [comment]
@cmltaWt0 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/devstack&entry.867055334=https://github.com/openedx/devstack/pull/885&entry.1484655318=https://github.com/cmltaWt0&entry.752974735=2022-01-18+17:39&entry.1917517419=2022-01-18+17:43&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
