### PR TITLE
Increase Docker Compose HTTP timeout

### PR DESCRIPTION
**Pull request by alanoe**
Motivation: reduce number of devstack provisioning failures in
unstable networks.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @alanoe! I've created [OSPR-4398](https://openedx.atlassian.net/browse/OSPR-4398) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@alanoe Thank you for your contribution. @jmbowman Can you give this a look when you have a chance?

**Review by jmbowman — APPROVED** [review]
Sorry for the late reply on such a trivial change; tests were failing in this repo for a few unrelated reasons and I was waiting for that to get sorted out.

**Comment by openedx-webhooks** [comment]
@alanoe 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/515&entry.1484655318=https://github.com/alanoe&entry.752974735=2020-04-17+13:00&entry.1917517419=2020-05-01+18:43&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
