### PR TITLE
TE-2639 Support for named release images

### PR DESCRIPTION
**Pull request by ghost**
(cherry picked from commit a76042b19aeb8fc8b02d93d3db4be783a54a0be1)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @victorcorreia1984! I've created [OSPR-2900](https://openedx.atlassian.net/browse/OSPR-2900) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@victorcorreia1984 Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by nedbat** [comment]
@jmbowman Correct me if I am wrong, but was the intent here that people would use the hawthorn branch of devstack to use Hawthorn?

**Comment by nedbat** [comment]
Hmm, I'm confused! @victorcorreia1984: it looks to me like this commit is already on master.  Are you seeing a problem?  This pull request should be unnecessary.

**Comment by ghost** [comment]
Hi, yes sorry this was a mistake!

**Comment by openedx-webhooks** [comment]
@victorcorreia1984 Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/374&entry.1484655318=https://github.com/victorcorreia1984&entry.752974735=2018-12-11+21:01&entry.1917517419=2018-12-12+11:17&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
