### PR TITLE
Hawthorn for Edraak Devstack

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarEdraak! I've created [OSPR-3334](https://openedx.atlassian.net/browse/OSPR-3334) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by ghost** [comment]
Oops!

**Comment by openedx-webhooks** [comment]
@OmarEdraak Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/400&entry.1484655318=https://github.com/OmarEdraak&entry.752974735=2019-04-29+13:26&entry.1917517419=2019-04-29+13:26&entry.2133058324=No) so we can improve your experience in the future.

**Comment by natabene** [comment]
@OmarEdraak If you plan to contribute to Open edX in the future, please sign the agreement, mentioned in the first comment, and send it to our legal team. We then will be able to review your code contributions and accept them.

**Pull request closed without merging**
