### PR TITLE
Add insights and analytics_api services

### PR DESCRIPTION
**Pull request by morenol**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-4864](https://openedx.atlassian.net/browse/OSPR-4864) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@morenol Thank you for your contribution. Please let me know once all tests are green.

**Comment by natabene** [comment]
@morenol Is this by any chance a BD PR?

**Comment by natabene** [comment]
@morenol @marcotuts What BD project is this with?

**Comment by morenol** [comment]
Hi @natabene, this is related to BD-1,(I think, that was the tag). It was not necessarily a requirement from that project, but I thought that it was a good idea to add this update here. Maybe we can just remove the BD tag, and get this as an open source contribution.

**Comment by marcotuts** [comment]
Ok to leave BD off if this was an open source contribution. Thanks @morenol !

**Comment by natabene** [comment]
@morenol @marcotuts  Got it, thanks for clarifying.

**Comment by natabene** [comment]
OSPR-4864

**Comment by natabene** [comment]
@morenol Can you let me know once the Travis check is green?

**Comment by natabene** [comment]
@morenol Just checking if you are still interested in pursuing this.

**Comment by morenol** [comment]
Hi @natabene, I have seen some movements towards the decentralization of the devstack and this PR is quite the opposite of that, so I am not sure if it is worth to keep working on this.

**Comment by regisb** [comment]
@morenol Would you like to change your PR to make it compatible with the new decentralized devstack? If you don't have time to work on this right now that's ok, we can close this and re-open it later.

**Comment by natabene** [comment]
@morenol This will be reviewed by @regisb  (thanks @regisb ).

**Comment by morenol** [comment]
Hi @regisb, yes. I think that I can do that.

**Comment by jmbowman** [comment]
The current plan is for each of these services to get it's own "devstack" of just the services it normally communicates with, but that's probably still a few months out (we just finished the first prototype of this for one service).  I suspect this PR may be the only chance to get them into a local dev environment in time for Koa, but given that we haven't had that so far I'm not sure how important it is for the Open edX community.  My initial instinct is that we'd probably take the PR if tests are passing, but I'm also ok with just closing it if you don't want to put more time into it.

@regisb , is there anything you'd want to add on this topic?
@macdiesel , would having these services available in devstack be of use to Data Engineering in the short term?

**Comment by jmbowman** [comment]
Gah, I hadn't reloaded the page in a few days, just saw the last few comments.  @regisb feel free to handle this, let me know if you want any help with it.

**Comment by macdiesel** [comment]
@jmbowman It's certainly something I would love to have ultimately, but I would put it towards the end of your list. We do not currently have any front end plans for insights for at least the next 6 months and possibly longer. Thanks for checking in.

**Comment by regisb** [comment]
Considering that it was just decided to remove edx-analytics-pipeline from the devstack ([DEPR-119](https://openedx.atlassian.net/browse/DEPR-119)), I believe we should close this. @morenol do you agree?

**Comment by openedx-webhooks** [comment]
@morenol Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/480&entry.1484655318=https://github.com/morenol&entry.752974735=2020-02-28+12:51&entry.1917517419=2020-12-28+15:31&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
