### PR TITLE
[Backport] Multiple devstack releases with one machine

### PR DESCRIPTION
**Pull request by arbrandes**
This is a backport of https://github.com/edx/devstack/pull/532 to ironwood.master.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @arbrandes! I've created [OSPR-4562](https://openedx.atlassian.net/browse/OSPR-4562) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@arbrandes Thank you for your contribution. @jmbowman Can you please have a look, this is ready for you.

**Comment by jmbowman** [comment]
Hmm, this is significantly bigger than the type of changes we normally make on a release branch, and #532 has been changed a fair bit since this was written.  Is there still a desire to get these changes into Ironwood?

**Comment by regisb** [comment]
Considering that Juniper is almost out the door, wouldn't it make more sense to merge this in the open-release/juniper.master branch? (which has [just been created](https://github.com/edx/devstack/tree/open-release/juniper.master)) The whole point of this PR is to make it possible to test older releases, right? So we would be able to test Ironwood from the Juniper branch.

**Comment by ztraboo** [comment]
@jmbowman @regisb @arbrandes With #532 @kdmccormick is looking at final review today before committing it. Additional changes were taking into consideration outside the `docker-compose` service `container_name` and `network` alias to make this work. I think we should definitely commit this to `open-release/juniper.master` and potentially `open-release/ironwood.master` since that's current stable release.

@kdmccormick Just merged #532 and wrote this forum post here.
https://discuss.openedx.org/t/multiple-isolated-devstacks-on-the-same-host/2277

**Comment by kdmccormick** [comment]
#532 has been merged.

I think this is a great change. However, I hesitate to recommend that it be merged into `juniper.master` right now. As a large diff in a repository with relatively low test coverage, there's potential that there are hidden bugs that we didn't find during code review. It might be best to let any such bugs shake out within the next few weeks, and then merge this into one of the follow-up releases.

Just my $0.02.

**Comment by arbrandes** [comment]
@jmbowman,
> this is significantly bigger than the type of changes we normally make on a release branch, and #532 has been changed a fair bit since this was written. Is there still a desire to get these changes into Ironwood?

There is definitely a desire for us at OpenCraft, as we have to regularly maintain (and backport fixes to) Ironwood instances.  In any case, and for what it's worth, I do intend to update this PR to reflect the changes ended up merged on #532.  :)

@regis
> Considering that Juniper is almost out the door, wouldn't it make more sense to merge this in the open-release/juniper.master branch? (which has just been created) The whole point of this PR is to make it possible to test older releases, right? So we would be able to test Ironwood from the Juniper branch.

The `juniper.master` branch of the devstack is much closer to master than `ironwood.master`, so porting it back there is an easy cherry-pick.  No changes necessary.  For `ironwood.master` it's a different story.  There are more containers, some have been removed, etc.  Hence, this backport.

Which is to say, Juniper should definitely _also_ get this, methinks.

Whether it's universally considered _necessary_ for Ironwood is debatable, of course.  At OpenCraft we'll definitely have a use for it.

@kdmccormick 
>  It might be best to let any such bugs shake out within the next few weeks, and then merge this into one of the follow-up releases.

Fair enough.  I, for one, will be testing this with Ironwood, Juniper, _and_ master going forward anyway (I already have these 3 devstacks installed simultaneously right now, as a matter of fact).  Probably more folks at OpenCraft, too.  We'll make sure to let you know if we find anything wrong. :)

**Comment by ztraboo** [comment]
> Considering that Juniper is almost out the door, wouldn't it make more sense to merge this in the open-release/juniper.master branch? (which has [just been created](https://github.com/edx/devstack/tree/open-release/juniper.master)) The whole point of this PR is to make it possible to test older releases, right? So we would be able to test Ironwood from the Juniper branch.

I made this #564 to handle this update.

cc: @arbrandes @regisb

**Comment by regisb** [comment]
@arbrandes Is this PR still relevant for Opencraft? The Ironwood branch is no longer officially supported, but if these changes are helpful to you guys, then I'll be happy to merge. Otherwise we should close this.

**Comment by natabene** [comment]
@bradenmacdonald Please advise on whether this is still relevant, now that we are on Koa, or can be closed. CC @nedbat @regisb @jmbowman

**Comment by bradenmacdonald** [comment]
I'll ask @arbrandes

**Comment by arbrandes** [comment]
@natabene, apologies for the delay.  This can be closed, as we don't have a need for it anymore.

**Comment by openedx-webhooks** [comment]
@arbrandes Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/538&entry.1484655318=https://github.com/arbrandes&entry.752974735=2020-05-19+23:17&entry.1917517419=2021-01-14+02:14&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
