### PR TITLE
docs: Clean up documentation.

### PR DESCRIPTION
**Pull request by dianakhuang**
- Removed out of date known issues.
- Cleaned up workflow commands.
- Removed references to out of date Pycharm instructions.

----

I've completed each of the following or determined they are not applicable:

- [ ] Made a plan to communicate any major developer interface changes (or N/A)

### CODE REVIEW

**Review by rgraber — COMMENTED** [review]
Why are we replacing the `lms-*` commands with `dev.*.lms` ? I usually use `lms-*`

**Comment by dianakhuang** [comment]
Mostly this is the better-supported convention? But I don't have strong feelings about it and can go either way.

**Comment by rgraber** [comment]
> Mostly this is the better-supported convention? But I don't have strong feelings about it and can go either way.

Actually this also brings up a question for me about why we have both and if that's more confusing than helpful. But I guess it makes sense to use dev.action.service since that's how it's described in the makefile.

**Comment by dianakhuang** [comment]
I'm not sure why we introduced a new one, but I feel like the `lms-` commands were kept around for backwards compatibility.

**Review by rgraber — APPROVED** [review]
I know we're looking for quick wins, so approving, but in the future it might be useful to have examples of what kinds of changes require a full restart

**Comment by rgraber** [comment]
> I know we're looking for quick wins, so approving, but in the future it might be useful to have examples of what kinds of changes require a full restart

Somehow I completely skipped over the examples that were already there. Made a request to add a line about how runserver occasionally just stops picking up changes because it doesn't feel like it.

**Pull request merged**
