### PR TITLE
Install npm packages before building static files in studio and lms

### PR DESCRIPTION
**Pull request by OmarIthawi**
WebPack wasn't succeeding. Now it is.

### How to Reproduce?
So sorry for providing no more details, but it's really hard to reproduce errors in `devstack`. So probably the error won't be reproducible on your machine.

```
$ cd devstack
$ git checkout master
$ git pull
$ make destroy
$ make dev.reset
```

Somewhere in the lines you'll get the error below while the LMS complains about an IOError because of a missing WebPack file:

```
Copying '/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/jquery_post.js'
Copying '/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/toolbar.profiling.js'
Copying '/edx/app/ecommerce/venvs/ecommerce/local/lib/python2.7/site-packages/debug_toolbar/static/debug_toolbar/js/toolbar.template.js'

2801 static files copied to '/edx/var/ecommerce/staticfiles', 424 unmodified.
python manage.py compress --force
Found 'compress' tags in:
	/edx/app/ecommerce/ecommerce/ecommerce/templates/coupons/offer.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/edx/checkout/receipt_not_found.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/404.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/edx/email_confirmation_required.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/coupons/coupon_app.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/oscar/checkout/payment_error.html
	/edx/app/ecommerce/ecommerce/ecommerce/programs/templates/programs/programoffer_list.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/coupons/_offer_error.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/courses/course_app.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/500.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/edx/credit/checkout.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/oscar/dashboard/refunds/refund_detail.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/bootstrap-demo.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/edx/error.html
	/edx/app/ecommerce/ecommerce/ecommerce/enterprise/templates/enterprise/enterpriseoffer_form.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/edx/base.html
	/edx/app/ecommerce/ecommerce/ecommerce/enterprise/templates/enterprise/enterpriseoffer_list.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/oscar/dashboard/orders/order_list.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/oscar/dashboard/orders/order_detail.html
	/edx/app/ecommerce/ecommerce/ecommerce/journals/templates/journals/journalbundleoffer_form.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/oscar/checkout/cancel_checkout.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/edx/checkout/receipt.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/oscar/checkout/sdn_failure.html
	/edx/app/ecommerce/ecommerce/ecommerce/programs/templates/programs/programoffer_form.html
	/edx/app/ecommerce/ecommerce/ecommerce/journals/templates/journals/journalbundleoffer_list.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/oscar/basket/basket.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/oscar/dashboard/refunds/refund_list.html
	/edx/app/ecommerce/ecommerce/ecommerce/templates/oscar/checkout/error.html
Compressing... done
Compressed 17 block(s) from 28 template(s) for 1 context(s).
docker exec -t edx.devstack.lms bash -c 'source /edx/app/edxapp/edxapp_env && cd /edx/app/edxapp/edx-platform/ && paver update_assets'
---> pavelib.assets.update_assets
---> pavelib.prereqs.install_node_prereqs
Node prereqs unchanged, skipping...
---> pavelib.assets.process_xmodule_assets
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
NO_PYTHON_UNINSTALL is set. No attempts will be made to uninstall old Python libs.
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/development.txt
xmodule_assets common/static/xmodule
		Finished processing xmodule assets.
mkdir_p path('common/static/common/js/vendor')
mkdir_p path('common/static/common/css')
mkdir_p path('common/static/common/css/vendor')
mkdir_p path('common/static/common/media')
mkdir_p path('common/static/common/media/vendor')
Copying vendor files into static directory


Captured Task Output:
---------------------

---> pavelib.assets.update_assets
---> pavelib.prereqs.install_node_prereqs
---> pavelib.assets.process_xmodule_assets
---> pavelib.prereqs.install_python_prereqs
---> pavelib.prereqs.uninstall_python_packages
pip install -q --disable-pip-version-check --exists-action w -r requirements/edx/development.txt
xmodule_assets common/static/xmodule
mkdir_p path('common/static/common/js/vendor')
mkdir_p path('common/static/common/css')
mkdir_p path('common/static/common/css/vendor')
mkdir_p path('common/static/common/media')
mkdir_p path('common/static/common/media/vendor')
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 201, in _run_task
    return do_task()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 198, in do_task
    return func(**kw)
  File "pavelib/utils/timer.py", line 39, in timed
    return wrapped(*args, **kwargs)
  File "pavelib/assets.py", line 948, in update_assets
    process_npm_assets()
  File "pavelib/assets.py", line 650, in process_npm_assets
    copy_vendor_library(library)
  File "pavelib/assets.py", line 619, in copy_vendor_library
    raise Exception('Missing vendor file {library_path}'.format(library_path=library_path))
Exception: Missing vendor file node_modules/backbone.paginator/lib/backbone.paginator.js

Makefile:218: recipe for target 'lms-static' failed
make: *** [lms-static] Error 1
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-2801](https://openedx.atlassian.net/browse/OSPR-2801) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by jmbowman** [comment]
The thing is, `paver update_assets` should be calling `npm install` anyway: https://github.com/edx/edx-platform/blob/master/pavelib/assets.py#L899 .  It should only be skipped if the `NO_PREREQ_INSTALL` environment variable is set or no changes are detected in `package.json`.  There may be a bug in [this logic](https://github.com/edx/edx-platform/blob/master/pavelib/prereqs.py#L90), though; we keep the hash of `package.json` under the `edx-platform` root directory, but the `node_modules` directory is kept in a volume which I think is recreated on each download of a new container image.  So we might hit some cases where paver thinks we've already installed those packages, but the directory has been recreated in the meantime.

I do hope that's the actual cause of that error, because we've been seeing it intermittently for quite a while.  We originally thought it was related to https://openedx.atlassian.net/browse/FEDX-500 , but maybe it is just a cache logic error.

**Comment by OmarIthawi** [comment]
@jmbowman that makes total sense! Please feel free to merge/close/whatever to this PR.

I hope that it will at least contribute to fixing the error. 

More importantly, I'm glad that this isn't just my computer playing mind games with me :sweat_smile:

**Comment by OmarIthawi** [comment]
@jmbowman How about having the `$ dev.reset` invalidates "that cache". Would that be possible?

I remember digging a lot in this part back in 2014. But my memory isn't helping right now.

**Comment by natabene** [comment]
@OmarIthawi Thanks for you contribution. @jmbowman Would you like to close or merge it?

**Comment by OmarIthawi** [comment]
I'm closing this PR since it probably needs a better fix, and I'm not sure that I have the capacity for it. The current solution works very for me. Please feel free to re-open and merge.

cc: @natabene @jmbowman

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/350&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2018-11-14+09:16&entry.1917517419=2018-12-03+10:32&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
