### PR TITLE
Use Docker's prune command for devstack destruction

### PR DESCRIPTION
**Pull request by rlucioni**
No need to reinvent the wheel here. I'm using `--force` since the script already prompts for confirmation.

### CODE REVIEW

**Review by clintonb — CHANGES_REQUESTED** [review]
We should only prune the things we know about for devstack. Pruning the entire system destroys things that aren't devstack. That's not good.

**Comment by rlucioni** [comment]
That's fair. To be clear, the prune command only removes unused data, so anything removed here would have been unused anyway. The command supports [filtering](https://docs.docker.com/engine/reference/commandline/system_prune/#filtering), but only by creation timestamp for now.

**Comment by clintonb** [comment]
Note that "unused" does not mean unwanted. For example, if I run that command with all of my containers stopped, it will get rid of all the containers and volumes. Only running containers/volumes would remain.

**Comment by rlucioni** [comment]
Yeah, good point.

**Pull request closed without merging**
