### PR TITLE
Fixed a spelling error - "machinge" to "machine" in Readme

### PR DESCRIPTION
**Pull request by 0xbhvn**
Change machinge to machine on line 95

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @thisisbhaven! I've created [OSPR-4995](https://openedx.atlassian.net/browse/OSPR-4995) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by regisb** [comment]
Hi @thisisbhaven! Can you please give a more informative title to your commit? For instance: "Fix tiny README typo". This is useful to understand that the typo occurs in a user-facing document, and not in code.

**Comment by natabene** [comment]
@thisisbhaven Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by natabene** [comment]
@thisisbhaven Just checking if you were able to finalize the agreement signing with out Legal team. Please let me know if you need any help.

**Comment by natabene** [comment]
@thisisbhaven We have not heard from you in a while, so I am closing this PR for now. Please feel free to re-open.

**Comment by openedx-webhooks** [comment]
@thisisbhaven Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/617&entry.1484655318=https://github.com/thisisbhaven&entry.752974735=2020-09-23+09:18&entry.1917517419=2020-12-17+02:22&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
