### PR TITLE
Feat:Auto-sync dependencies between code and virtual env for lms   

### PR DESCRIPTION
**Pull request by XLAR-8**
Solves issue: [devstack/issues/1028
](https://github.com/openedx/devstack/issues/1028)

description:
Auto-sync dependencies between code and virtual env for LMS for now, can be extended for other services too.

----

I've completed each of the following or determined they are not applicable:

- [ ] Made a plan to communicate any major developer interface changes (or N/A)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @XLAR-8!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hi @XLAR-8, thank you for this contribution!

As the bot mentioned, the next step will be for you to sign the Open edX Contributor Agreement.

Then we can enable tests for this PR, and get it into the review queue.

**Comment by XLAR-8** [comment]
@itsjeyd I have already sign the Open edX Contributor Agreement.

**Comment by itsjeyd** [comment]
@XLAR-8 Great! As the bot mentioned [above](https://github.com/openedx/devstack/pull/1068#issuecomment-1546749492), the next step will be to trigger another run of the CLA check; you can do that by editing (and saving) the PR title.

**Comment by itsjeyd** [comment]
Hey @XLAR-8, now that the CLA check passed, could you please rebase your branch on latest master (or merge the latest commits)? Once that's done we'll kick off a test run.

**Comment by e0d** [comment]
Updating via a merge commit, which will re-run the tests.

**Comment by e0d** [comment]
@XLAR-8 looks like several of the provisions are failing with this change, can you have a look?

**Comment by itsjeyd** [comment]
@XLAR-8 A friendly reminder to have a look at the tests that are failing here.

Once everything is green we'll line up your changes for engineering review.

**Comment by itsjeyd** [comment]
Hi @XLAR-8, just checking in to see if we should keep this PR open?

**Comment by openedx-webhooks** [comment]
@XLAR-8 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/devstack&entry.867055334=https://github.com/openedx/devstack/pull/1068&entry.1484655318=https://github.com/XLAR-8&entry.752974735=2023-05-13+21:04&entry.1917517419=2023-07-19+04:28&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
