### PR TITLE
Fix NFS error with volume not mounting for `/Users` directory on Catalina

### PR DESCRIPTION
**Pull request by ztraboo**
Details: https://discuss.openedx.org/t/nfs-volumes-wont-mount-devstack-mac-catalina/1944

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ztraboo! I've created [OSPR-4420](https://openedx.atlassian.net/browse/OSPR-4420) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@ztraboo Thank you for your contribution. Can you look into the failing Travis check?

**Comment by kdmccormick** [comment]
@ztraboo The eCommerce failure is a known issue that we just fixed. If you push a new commit a few hours from now, the build should pass.

BTW - I'm not going to be able to earnestly review this because I don't have a Mac. It would be good to get reviews from someone running Mojave and someone running Catalina, if we can.

**Comment by ztraboo** [comment]
> @ztraboo The eCommerce failure is a known issue that we just fixed. If you push a new commit a few hours from now, the build should pass.
> 
> BTW - I'm not going to be able to earnestly review this because I don't have a Mac. It would be good to get reviews from someone running Mojave and someone running Catalina, if we can.

@kdmccormick What fix was done to make this ecommerce change? I noticed this same error on my devstack master release too. Would a new docker ecommerce image need to be recreated with that change? Is that why you mentioned wait a couple hours then resubmit a pull request?

I'm running Mac OS X Catalina 10.15.4

**Comment by kdmccormick** [comment]
@ztraboo https://github.com/edx/configuration/pull/5764 fixed an issue with ecommerce's configuration. Now that the [edX ecommerce Docker image](https://hub.docker.com/r/edxops/ecommerce) has rebuilt, [the tests for this PR](https://travis-ci.org/github/edx/devstack/builds/679412613), which failed for the ecommerce shard, should pass if you re-trigger them.

I recommend you re-trigger the build for this PR by running `git commit --amend` on this branch and then force-pushing with `git push -f`.

I'm mentioning that I don't have a Mac so that someone at edX who runs OS X can review this :)

**Comment by ztraboo** [comment]
> @ztraboo [edx/configuration#5764](https://github.com/edx/configuration/pull/5764) fixed an issue with ecommerce's configuration. Now that the [edX ecommerce Docker image](https://hub.docker.com/r/edxops/ecommerce) has rebuilt, [the tests for this PR](https://travis-ci.org/github/edx/devstack/builds/679412613), which failed for the ecommerce shard, should pass if you re-trigger them.
> 
> I recommend you re-trigger the build for this PR by running `git commit --amend` on this branch and then force-pushing with `git push -f`.
> 
> I'm mentioning that I don't have a Mac so that someone at edX who runs OS X can review this :)

@kdmccormick I re-pushed my commit with an amend comment.

**Comment by openedx-webhooks** [comment]
@ztraboo Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/521&entry.1484655318=https://github.com/ztraboo&entry.752974735=2020-04-25+13:57&entry.1917517419=2020-04-27+16:18&entry.2133058324=No) so we can improve your experience in the future.

**Comment by kdmccormick** [comment]
@ztraboo Sorry for the continued test failures. It looks like the configuration fix I mentioned earlier only solved part of the problem. I need to step back at this point, but I opened a ticket to investigate the test failures.

**Comment by natabene** [comment]
@kdmccormick Is this blocked until further notice from you?

**Comment by kdmccormick** [comment]
@natabene Yeah. I'll comment here again when tests are fixed.

**Comment by kdmccormick** [comment]
@ztraboo I think tests have been fixed. If you rebase your commit onto master, then hopefully tests will pass.

**Comment by ztraboo** [comment]
> @ztraboo I think tests have been fixed. If you rebase your commit onto master, then hopefully tests will pass.

@kdmccormick Ok giving this a shot again. I rebased on top of master my change.

**Comment by ztraboo** [comment]
@kdmccormick @natabene All tests have passed. Need second reviewer with Mac to test NFS change.

**Comment by jmbowman** [comment]
Hmm, this may fix it for Catalina but seems to break it for earlier versions (I tested on Mojave).  Probably need to detect the OS version and use the appropriate path based on that.

**Comment by ztraboo** [comment]
> Hmm, this may fix it for Catalina but seems to break it for earlier versions (I tested on Mojave). Probably need to detect the OS version and use the appropriate path based on that.

@jmbowman I made this change here to account for OS X Catalina (10.15). I wasn't sure if I needed to do a `-ge 15` for the minor release for major release 10 or not for any release after Catalina. Let me know what you think about my change.
https://github.com/CUCWD/devstack/commit/2ecdcba9f8ae42b1c0944fb2841968da68ce7ad6

**Comment by jmbowman** [comment]
The next macOS release will probably be out in September or October, and is likely to behave like Catalina in this respect.  It would be nice for this to handle such future releases, especially since this is likely to go in the Juniper Open edX release and Koa may not be out by then.

I'll try to test this under Mojave again tomorrow, but not expecting any problems.

**Comment by ztraboo** [comment]
> The next macOS release will probably be out in September or October, and is likely to behave like Catalina in this respect. It would be nice for this to handle such future releases, especially since this is likely to go in the Juniper Open edX release and Koa may not be out by then.
> 
> I'll try to test this under Mojave again tomorrow, but not expecting any problems.

@jmbowman Updated the code to handle Catalina (10.15.*) release or newer.
https://github.com/edx/devstack/pull/521/commits/8c4ac8731aa23ef469e9286f91b234736e142277

**Comment by ztraboo** [comment]
@jmbowman Not sure why some of the checks are failing due to requirements.txt not found. I didn't change any of that. Please advise.

> Could not locate requirements.txt. Override the install: key in your .travis.yml to install dependencies.

**Comment by ztraboo** [comment]
@jmbowman Please review since the test have passed now.

**Comment by jmbowman** [comment]
I get an error running this on Mojave:

```
== Setting up nfs...
./setup_native_nfs_docker_osx.sh: line 62: [[: 10[0]: syntax error: invalid arithmetic operator (error token is "[0]")
```

**Comment by natabene** [comment]
@ztraboo Pinging to see if you still interested in this and can address the error mentioned.

**Comment by ztraboo** [comment]
@natabene I don’t have Mojave install to test this from. Really just need to know how to conditionally handle this OS. @jmbowman Any help with this?

**Comment by jmbowman** [comment]
Sorry for the long delay in replying to this.  The code you used to populate `OSX_VERSION_ARRAY` doesn't seem to work correctly, it just outputs the major version number ("10").  But the following snippet from the same blog post does work as advertised to get the major version number:

> `$(sw_vers -productVersion | awk -F. '{ print $2; }')`

Could you just assign that to a variable and use it in the condition?  (Technically you could also just skip the `[0]` in your current code, but I'm a little worried that it could yield an array on some OS versions and a value on others.)

**Comment by natabene** [comment]
@ztraboo Just checking if you had a chance to address Jeremy's feedback.

**Comment by natabene** [comment]
@ztraboo Closing this for now, as we have not heard back in a while. Please feel free to re-open.

**Comment by openedx-webhooks** [comment]
@ztraboo Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/521&entry.1484655318=https://github.com/ztraboo&entry.752974735=2020-04-25+13:57&entry.1917517419=2021-02-03+01:43&entry.2133058324=No) so we can improve your experience in the future.

**Comment by ztraboo** [comment]
@natabene I understand. If someone else wants to complete this I'm fine with that too.

**Pull request closed without merging**
