### PR TITLE
fix: increase compose command timeout so that devstack make commands don't fail

### PR DESCRIPTION
**Pull request by XLAR-8**
Solves issue: [devstack/issues/1031](https://github.com/openedx/devstack/issues/1031)

Description:
Increaing Docker Compose HTTP timeout, in seconds, so that devstack make commands do not fail.

----

I've completed each of the following or determined they are not applicable:

- [ ] Made a plan to communicate any major developer interface changes (or N/A)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @XLAR-8!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hi @XLAR-8, thank you for this contribution!

As the bot mentioned, the next step will be for you to sign the Open edX Contributor Agreement.

Then we can enable tests for this PR, and get it into the review queue.

**Comment by XLAR-8** [comment]
@itsjeyd can you please check again, I have signed contribution form ?

**Comment by itsjeyd** [comment]
Thanks for the update @XLAR-8. Could you please update the title of the PR to trigger a re-run of the CLA check?

> Once you've signed the CLA, [...] you can re-run the CLA check by editing the PR title.

**Comment by XLAR-8** [comment]
@itsjeyd  done

**Comment by itsjeyd** [comment]
Thank you @XLAR-8!

The CLA check passed, so we're ready to move forward with next steps.

Could you please update your branch so that it includes the latest changes from master? Once that's done we'll enable CI checks for your changes.

**Comment by e0d** [comment]
Updating via a merge commit which will re-run the tests.

**Comment by e0d** [comment]
Please amend your commit messages to follow the conventional commit format described [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type
).

**Comment by itsjeyd** [comment]
@XLAR-8 A friendly reminder to update your commit messages. This will fix the build :)

Once everything is green we'll line up your changes for engineering review.

**Comment by XLAR-8** [comment]
@itsjeyd @e0d done.

**Comment by itsjeyd** [comment]
@XLAR-8 Thanks for the update. It looks like one of your commit messages will need further adjustment. From the commitlint output:

```
⧗   input: Fix- increased compose command timeout so that devstack make commands don't fail
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
```

What that tells me is that if you change 

```
Fix- increased compose command timeout so that devstack make commands don't fail
```

to

```
fix: increase compose command timeout so that devstack make commands don't fail
```

... the build should turn green.

**Comment by XLAR-8** [comment]
@itsjeyd this is done

**Comment by itsjeyd** [comment]
Hey @XLAR-8, it looks like you updated the title of the PR, but not the commit message? I'm still seeing `Fix- increased compose command timeout so that devstack make commands don't fail` on the [Commits](https://github.com/openedx/devstack/pull/1066/commits) tab:

image

[This page](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message) explains how to change commit messages and overwrite commits that have already been pushed to GitHub.

**Comment by timmc-edx** [comment]
The branch now seems to contain about 55 more commits than expected, at least according to GitHub. Maybe a rebase error?

**Comment by itsjeyd** [comment]
Hi @XLAR-8, just checking in to see if you're still planning to work on this PR?

**Comment by itsjeyd** [comment]
Hi @XLAR-8! Just a quick update that I'm closing this PR now because it is stale. You may reopen this pull request, or open a new one, when you have time to come back to this work. Thanks!

**Comment by openedx-webhooks** [comment]
@XLAR-8 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/devstack&entry.867055334=https://github.com/openedx/devstack/pull/1066&entry.1484655318=https://github.com/XLAR-8&entry.752974735=2023-05-11+11:36&entry.1917517419=2023-09-13+11:53&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@XLAR-8 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/devstack&entry.867055334=https://github.com/openedx/devstack/pull/1066&entry.1484655318=https://github.com/XLAR-8&entry.752974735=2023-05-11+11:36&entry.1917517419=2023-09-13+11:53&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
