### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by mdaldoss**
Added support for compiling single theme sass and or static

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mdaldoss! I've created [OSPR-4610](https://openedx.atlassian.net/browse/OSPR-4610) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@mdaldoss Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by natabene** [comment]
@mdaldoss We have not heard from you in a while, so I will close this PR for now. Please feel free to re-open in the future.

**Comment by openedx-webhooks** [comment]
@mdaldoss Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/542&entry.1484655318=https://github.com/mdaldoss&entry.752974735=2020-05-29+21:00&entry.1917517419=2020-07-07+18:45&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
