### PR TITLE
Replace all .(lms|cms).(\w+|_)?\.json to .(lms|cms).(\w+|_)?\.yml

### PR DESCRIPTION
**Pull request by gabor-boros**
Replace all .(lms|cms).(\w+|_)?\.json to .(lms|cms).(\w+|_)?\.yml as a follow up on https://github.com/edx/edx-documentation/pull/1887

JIRA tickets: None

Discussions:
* https://github.com/edx/edx-documentation/pull/1887

Dependencies: None

Sandbox URL: N/A

Merge deadline: "None"

Testing instructions:

N/A

### Reviewers

- [ ] @toxinu 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @gabor-boros! I've created [OSPR-4981](https://openedx.atlassian.net/browse/OSPR-4981) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@gabor-boros Thank you for your contribution. Please let me know once all tests are green.

**Comment by gabor-boros** [comment]
@natabene I'll ping you when everything is green, thank you

**Comment by gabor-boros** [comment]
@natabene I'm not sure that the failing tests are failing because of me. I mean I changed rst files and docker images not found in the tests. Could you please restart the tests?

**Comment by toxinu** [comment]
Looks good to merge 👍🏻

**Comment by gabor-boros** [comment]
@natabene The PR can be reviewed from your side too, also as I mentioned above: I'm not sure that the failing tests are failing because of my changes

**Comment by openedx-webhooks** [comment]
@gabor-boros 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/devstack&entry.867055334=https://github.com/edx/devstack/pull/613&entry.1484655318=https://github.com/gabor-boros&entry.752974735=2020-09-18+08:56&entry.1917517419=2020-09-21+08:05&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
