### PR TITLE
feat: add frontend-app-profile to DevStack

### PR DESCRIPTION
**Pull request by cmltaWt0**
Changes:
- update README
- add frontend-app-account service to docker-compose.yml
- add frontend-app-account service to docker-compose-host.yml
- add frontend-app-account to EDX_SERVICES in options.mk
- add frontend-app-account repo to non_release_* repos in repo.sh

Since Profile MFE is a part of Lilac+ release - there is clear demand to have it in default Devstack suit.

Issues:
- enabling Profile MFE in LMS UI requires following actions which can be done in lms provision step but probably must be done in configuration repo during docker image preparation step

Enabling Profile MFE in UI:
```
diff --git a/provision-lms.sh b/provision-lms.sh
index cd162ee..4caf868 100755
--- a/provision-lms.sh
+++ b/provision-lms.sh
 # Enable MFE
+docker-compose exec -T lms bash -e -c 'source /edx/app/edxapp/edxapp_env && python /edx/app/edxapp/edx-platform/manage.py lms waffle_flag --list --settings=devstack_docker | grep learner_profile.redirect_to_microfrontend || python /edx/app/edxapp/edx-platform/manage.py lms waffle_flag --create --everyone learner_profile.redirect_to_microfrontend --settings=devstack_docker'
```
Site Configuration must be updated with this:
```
{
  "ENABLE_PROFILE_MICROFRONTEND": true
}
```
Also we have to add `PROFILE_MICROFRONTEND_URL = 'http://localhost:1995/u/'` to lms.yml to `devstack.py`

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @cmltaWt0! I've created [OSPR-6437](https://openedx.atlassian.net/browse/OSPR-6437) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@cmltaWt0 Thank you for your contribution, is this ready for our review?

**Comment by cmltaWt0** [comment]
@natabene Yeap. Totally. Thanks!

**Review by dianakhuang — APPROVED** [review]
This looks good to me. I'm going to merge it. Thanks @cmltaWt0 !

**Comment by openedx-webhooks** [comment]
@cmltaWt0 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/devstack&entry.867055334=https://github.com/openedx/devstack/pull/898&entry.1484655318=https://github.com/cmltaWt0&entry.752974735=2022-02-04+14:09&entry.1917517419=2022-02-22+16:44&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
