### PR TITLE
Fix typo in prorams/README.md

### PR DESCRIPTION
**Pull request by seanluong**
----

I've completed each of the following or determined they are not applicable:

- [X] Made a plan to communicate any major developer interface changes (or N/A)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @seanluong! I've created [OSPR-6578](https://openedx.atlassian.net/browse/OSPR-6578) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@seanluong Thank you for the contribution! Once you have signed the Contributor Agreement and it has been processed, you will receive a confirmation via email from our Legal team. We then will be able to review this and all your future code contributions.

**Comment by seanluong** [comment]
> @seanluong Thank you for the contribution! Once you have signed the Contributor Agreement and it has been processed, you will receive a confirmation via email from our Legal team. We then will be able to review this and all your future code contributions.

@natabene I signed it this morning. I have also received the confirmation in my inbox.

**Comment by natabene** [comment]
@seanluong Thank you, your CLA check will clear soon. I will let you know once this happens.

**Comment by openedx-webhooks** [comment]
@seanluong Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/devstack&entry.867055334=https://github.com/openedx/devstack/pull/917&entry.1484655318=https://github.com/seanluong&entry.752974735=2022-04-06+03:03&entry.1917517419=2022-05-19+01:11&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
Hello @seanluong: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

**Comment by natabene** [comment]
@seanluong Apologies for a long delay, I closed/reopened to get the check going, and it green now.

**Review by rgraber — APPROVED** [review]
LGTM if tests pass on update. Please fix commit message to use conventional commits and fix typo (prorams -> programs). Conventional commit docs: https://github.com/openedx/open-edx-proposals/blob/master/oeps/best-practices/oep-0051-bp-conventional-commits.rst

**Comment by rgraber** [comment]
Why did openedx-webhooks remove the Waiting on Author tag? We won't be able to merge until the commit title is fixed.

**Comment by natabene** [comment]
@rgraber That tag is actually set manually. Waiting on Author is normally reserved for earlier stages in the process, e.g. when PR is still a draft, or if author is still fixing tests before the first review. Once PR is ready to be handed over to a 2U engineer for review, I set it to In Review, indicating that it is being actively being reviewed. I included back and forth in that status, too. However, if it is more convenient for you to set it to Waiting on Author, please feel free to do so [here](https://github.com/orgs/openedx/projects/19/views/4).

**Comment by openedx-webhooks** [comment]
@seanluong 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/devstack&entry.867055334=https://github.com/openedx/devstack/pull/917&entry.1484655318=https://github.com/seanluong&entry.752974735=2022-04-06+03:03&entry.1917517419=2022-06-03+13:31&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
