### PR TITLE
Convert README to .rst

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
BTW, I did this with:
```
pandoc --from=markdown --to=rst --reference-links --reference-location=section --columns=79 README.md > README.rst
```

**Comment by nedbat** [comment]
@clintonb @jbarciauskas @jmbowman ?

**Review by clintonb — APPROVED** [review]
Why RST over MD?

**Comment by nedbat** [comment]
Because everything else in the edx repos are .rst, no?

**Pull request merged**
