### PR TITLE
Added Support for Docker Sync

### PR DESCRIPTION
**Pull request by clintonb**
Docker Sync will alleviate some of the filesystem issues on OS X.

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/ecommerce @efagin @robrap @gsong @staubina @feanil

**Comment by EugenMayer** [comment]
very nice comprehensive performance test here https://openedx.atlassian.net/wiki/display/OpenDev/Docker+Sync !

your test probably do only reflect reads, which are slow, but writes are even slower, the difference should then be about 50-60 times slower then native/docker-sync driven.

did you benchmark using native_osx or unison? You should in any case upgrade to docker-sync 0.4.6, a lot of bugfixes have been made to stabalize the 0.4.x branch, which has been a hard ride @clintonb

**Comment by EugenMayer** [comment]
Also since you probably think about offering windows support, docker-sync now supports windows with docker for windows + ubuntu shell WSL: could be a setup for you too https://github.com/EugenMayer/docker-sync/wiki/docker-sync-on-Windows

**Comment by clintonb** [comment]
Thanks @EugenMayer, for your feedback/suggestions AND your work on Docker Sync! I plan to run additional tests sometime next week.

**Comment by EugenMayer** [comment]
@clintonb well wouldnt we OSX devs otherwise kill ourselfs with a coffein shock during the coffee breaks while app stacks start, execute, run tests, compile assets or just process a request.

thanks for the heads up!

**Pull request merged**
