### PR TITLE
Add all targets to PHONIES

### PR DESCRIPTION
**Pull request by kdmccormick**
```
'make dev.provision' was trying to provision
the 'o' service, due strangeness related to the fact
that Makefiles were designed for compiling C
programs (which have .o intermediate files).

Fix the issue by adding all rules to PHONIES,
which tells Make that none of the targets are
real files.

Co-authored-by: Tim McCormack <tmccormack@edx.org>
```

### CODE REVIEW

**Comment by timmc-edx** [comment]
Thoughts on including other targets as well, such as `update-db` and `lms-shell`? I'm not sure which ones are most likely to cause problems.

Also, apparently one common Makefile style guide recommends putting `.PHONY: foo` above each target `foo:`, but I'm not sure I can stomach that. :-P

**Comment by timmc-edx** [comment]
(I see a total of 77 targets we could include, not counting pattern rules.)

**Comment by kdmccormick** [comment]
@timmc-edx Whoops, good catch. My script wasn't grabbing targets with dashes.

I've seen that recommendation before as well, and I lean towards just maintaining a big blob of phonies at the top instead of peppering the noise throughout the file. I can definitely polish my PHONIES-generation script and push it to repo-tools if that's something people would find useful.

**Comment by timmc-edx** [comment]
You'll want numbers as well, for `e2e-shell` and `e2e-tests`.

This is what I ended up with, for reference: `grep '^[^:%]+(?=:)' -Po ~/openedx/devstack/Makefile | grep -v '\t|#' -P | grep '[a-z]'` ("Any static pattern that isn't all uppercase.")

**Comment by kdmccormick** [comment]
How about now?

**Review by timmc-edx — APPROVED** [review]

**Comment by kdmccormick** [comment]
[The Travis failure](https://travis-ci.org/edx/devstack/jobs/640876409?utm_medium=notification&utm_source=github_status) seems to be unrelated and is also occurring on Master.

**Pull request merged**
