### PR TITLE
docs: update superuser username in the getting_started.rst file

### PR DESCRIPTION
**Pull request by hsinkoff**
Update the docs to include the correct email domain for the username.
----

I've completed each of the following or determined they are not applicable:

- [X] Made a plan to communicate any major developer interface changes (or N/A)
-   N/A

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @hsinkoff!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by itsjeyd** [comment]
Hey @hsinkoff, it looks like the PR bot marked this as an [open source contribution](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3548807177/Community+Contributions+Project+Manager#Community-Contributed-Pull-Requests-Overview), and I'm wondering if that's correct (based on the fact that you're a member of both https://github.com/edx and https://github.com/openedx)?

Please let me know if you think we can remove the label.

CC @mphilbrick211

**Comment by hsinkoff** [comment]
[itsjeyd](https://github.com/itsjeyd),

I believe that the open-source-contribution label can be removed. @jristau1984 is helping me get added to the correct group so that will not show up on future PRs.

**Comment by itsjeyd** [comment]
@hsinkoff OK, I removed the label.

**Review by rgraber — APPROVED** [review]
LGTM

**Comment by rgraber** [comment]
Not sure why it's failing the Mac ci check. Checking with arch-bom.

**Pull request merged**
