### PR TITLE
Add Common issues section to README.

### PR DESCRIPTION
**Pull request by vkaracic**
These are some that I have saved in an Everest note.

### CODE REVIEW

**Comment by vkaracic** [comment]
Ping @clintonb

**Comment by clintonb** [comment]
@edx/docker-devstack-working-group please review

**Review by jmbowman — APPROVED** [review]
I think we can fix the code to prevent most of these problems from occurring, but documenting the workarounds is a good start.

**Comment by vkaracic** [comment]
I don't think more than one reviewer is necessary for this. Merging.

**Pull request merged**
