### PR TITLE
WIP: Migrate Makefile calls to use compose plugin syntax

### PR DESCRIPTION
**Pull request by VanDavv**
I've encountered an issue while trying to setup devstack on Debian 12 with fresh Docker installation.

Official docker installation instructions available [here](https://docs.docker.com/engine/install/debian/#install-docker-engine) encourage users to install docker along with two plugins: Buildx and Compose

This allows developers to both utilize multi-arch builds with Buildx and to utilize the yaml-based approach in setting up containers with Compose

However, the way to use the docker compose, as installed by default, is by calling

```
docker compose ...
```

Whereas the "old" way of using it, by installing a Python script, was by calling

```
docker-compose ...
```

This PR changes the calls from `docker-compose` to `docker compose` in the Makefile of the devstack. 
People who might be affected negatively by this change are the developers who still use the docker compose installed outside the plugin. It can be mitigated by installing compose plugin by running

```
sudo apt-get install docker-compose-plugin
```
Without this PR, people who followed official Docker docs will have to install docker compose once again, as a Python script, to cover for the syntax change of the command

Here are my logs as I tried to use the Makefile with fresh docker and compose installation

```
$ make dev.pull.lms+frontend-app-learning
make[1]: Entering directory '/home/vandavv/dev/edx/edx-devstack'
docker-compose pull --include-deps $(echo lms+frontend-app-learning | tr + " ")
/bin/sh: 1: docker-compose: not found
make[1]: *** [Makefile:208: impl-dev.pull.lms+frontend-app-learning] Error 127
make[1]: Leaving directory '/home/vandavv/dev/edx/edx-devstack'
Would you like to assist devstack development by sending anonymous usage metrics to edX? Run `make metrics-opt-in` to learn more!
make: *** [Makefile:205: dev.pull.lms+frontend-app-learning] Error 2
```

```
$ docker compose version
Docker Compose version v2.19.1
```

With this PR, the command `make dev.pull.lms+frontend-app-learning` was completed successfully

## EDIT

I have also updated different provisioning scripts to use the new non-hyphen syntax, but introducing those would require a lot of testing I believe. Will update this PR to be a draft PR and will test on my side whether there are any other implications of moving from `docker-compose` to `docker compose`

----

I've completed each of the following or determined they are not applicable:

- [ ] Made a plan to communicate any major developer interface changes (or N/A)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @VanDavv!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.




:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by VanDavv** [comment]
I've pushed the migrated provisioning scripts as I was successfully able to run `make dev.provision` with the updated files. Will leave it as is for now and fall back to Python script

**Comment by itsjeyd** [comment]
Hey @VanDavv, thank you for your contribution!

Please follow the steps for signing a Contributor Agreement that the PR bot mentioned [above](https://github.com/openedx/devstack/pull/1128#issuecomment-1647493352).

Once that's done we can proceed with enabling tests for this PR.

**Comment by itsjeyd** [comment]
Hi @VanDavv, just checking in to see if you already had a chance to sign the Contributor Agreement?

**Comment by itsjeyd** [comment]
Hey @VanDavv, just checking in to see if you're still planning to continue working on this PR?

**Comment by itsjeyd** [comment]
Hi @VanDavv, just a quick update that we're closing this PR now because it is stale. You may reopen this pull request, or open a new one, when you have time to come back to this work.

**Comment by openedx-webhooks** [comment]
@VanDavv Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/devstack&entry.867055334=https://github.com/openedx/devstack/pull/1128&entry.1484655318=https://github.com/VanDavv&entry.752974735=2023-07-24+08:53&entry.1917517419=2023-09-26+06:34&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@VanDavv Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/devstack&entry.867055334=https://github.com/openedx/devstack/pull/1128&entry.1484655318=https://github.com/VanDavv&entry.752974735=2023-07-24+08:53&entry.1917517419=2023-09-26+06:34&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
